[package]
name = "logicle-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
logicle= { git = "https://github.com/tercen/logicle", tag = "0.1.0" }
 


